import type { NoticeDetailData } from "./types";

export const MOCK_NOTICE_DETAIL: NoticeDetailData = {
  id: "n1",
  title: "DIVE INTO CHANGE: 변화하는 아트웨어와 글로벌 미술시장",
  category: "강연/특강",
  department: "예술",
  date: "2026.04.27",
  deadline: "2026.05.02",
  deadlineTime: "18:00:00",
  dDay: 5,
  author: "예술경영지원센터",
  target: "관심 있는 누구나",
  applyMethod: "온라인 신청",
  views: 342,
  isBookmarked: false,
  bodyText: "본문 내용입니다.",
  bodyHtml: "",
  contentHtml: "<p>본문 내용입니다.</p>",
  contentStats: {
    image_count: 0,
    table_count: 0,
    file_count: 1,
  },
  attachments: [
    {
      id: 1,
      fileKey: "sample.pdf",
      originalName: "sample.pdf",
      ext: "pdf",
      fileType: "DOCUMENT",
      mimeType: "application/pdf",
      fileSize: 102400,
      checksum: null,
      sourceUrl: "https://example.com/sample.pdf",
      localPath: null,
      downloadOk: true,
      extractedText: null,
      extractedChars: null,
      parser: null,
      parseQuality: null,
      parseOk: null,
      downloadCached: null,
      createdAt: null,
    },
  ],
  originalUrl: "https://example.com/notice/123",
  tags: ["#문화체육관광부", "#예술경영지원센터", "#아트웨어", "#미술시장"],
};
